---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/instance: todo-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-app
      app.kubernetes.io/instance: todo-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-app
        app.kubernetes.io/instance: todo-node
    spec:
      containers:
        - name: main
          image: todo:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RELEASE_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: todo-app-cluster
                  key: ERLANG_COOKIE
          ports:
            - name: epmd
              containerPort: 4369
              protocol: TCP