---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc-headless
  namespace: default
  labels:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/instance: todo-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/instance: todo-node